name: landofile-editor

services:
  node:
    type: node:20
    build:
      - npm install
    command: vite --host 0.0.0.0
    port: 5173
    ssl: true
    sslExpose: false
  nginx:
    type: nginx:1.25
    webroot: public

tooling:
  npm:
    service: node
  node:
    service: node
  vite:
    service: node
  build:
    service: node
    cmd: npm run build
  preview:
    service: node
    cmd: npm run preview

proxy:
  node:
    - editor.lndo.site:5173
  nginx:
    - editor.lndo.site/public
